export const actionTypes = {
  SET_CATEGORY_ID: "SET_CATEGORY_ID",
  SET_QUIZ_QUESTIONS: "SET_QUIZ_QUESTIONS",
  INCREMENT_CURRENT_QUESTION_INDEX: "INCREMENT_CURRENT_QUESTION_INDEX",
  SET_ANSWER: "SET_ANSWER",
  SET_RESULTS: "SET_RESULTS",
  TAKE_ANOTHER_QUIZ: "TAKE_ANOTHER_QUIZ",
};
